spring.application.name=studyIF

# Conexão com MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/study_if?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.session.jdbc.initialize-schema=always

server.port=${PORT:8080}

# OAuth2 - Google
spring.security.oauth2.client.registration.google.client-id=995532909888-11qc5laqvbi4cahtqiitmsogve9km5un.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

# Sessão persistente (30 dias)
server.servlet.session.cookie.max-age=2592000
server.servlet.session.timeout=30d
